<?php

namespace pizzashop\tests\commande;

use Faker\Factory;
use Illuminate\Database\Capsule\Manager as DB;
use pizzashop\shop\domain\dto\commande\CommandeDTO;
use pizzashop\shop\domain\dto\item\ItemDTO;
use pizzashop\shop\domain\entities\catalogue\Produit;
use pizzashop\shop\domain\entities\catalogue\Taille;
use pizzashop\shop\domain\entities\commande\Commande;
use pizzashop\shop\domain\entities\commande\Item;
use pizzashop\shop\domain\service\catalogue\CatalogueService;
use pizzashop\shop\domain\service\commande\ServiceCommande;
use Ramsey\Uuid\Uuid;

class ServiceCommandeTest extends \PHPUnit\Framework\TestCase {

    private static $commandeIds = [];
    private static $itemIds = [];
    private static $serviceProduits;
    private static $serviceCommande;
    private static $faker;

    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass();
        $dbcom = __DIR__ . '/../../config/commande.db.ini';
        $dbcat = __DIR__ . '/../../config/catalog.db.ini';
        $db = new DB();
        $db->addConnection(parse_ini_file($dbcom), 'commande');
        $db->addConnection(parse_ini_file($dbcat), 'catalog');
        $db->setAsGlobal();
        $db->bootEloquent();

        self::$serviceProduits = new CatalogueService();
        self::$serviceCommande = new ServiceCommande(self::$serviceProduits, new \Monolog\Logger('test'));
        self::$faker = Factory::create('fr_FR');
        self::fillDB();
        print_r(self::$commandeIds);
    }

    public static function tearDownAfterClass(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        self::cleanDB();
    }


    private static function cleanDB(){
        foreach (self::$commandeIds as $id){
            Commande::find($id)->delete();
        }
        foreach (self::$itemIds as $id){
            Item::find($id)->delete();
        }
    }
    private static function fillDB() {
        //Create 2 to 5 commandes DTO with faker
        //Create 1 to 5 items DTO for each commande DTO with faker
        //Use the service to create the commandes with creerCommande(CommandeDTO): CommandeDTO
        //Verify that the returned CommandeDTO is the same as the one created

        for ($i = 0; $i < self::$faker->numberBetween(2, 5); $i++) {
            $commandeDTO = new CommandeDTO(
                Uuid::uuid4()->toString(), //Commande id

                self::$faker->dateTimeBetween('-1 year', 'now')
                    ->format('Y-m-d H:i:s'), //Commande date

                self::$faker->randomElement([
                    Commande::LIVRAISON_SUR_PLACE, Commande::LIVRAISON_A_EMPORTER, Commande::LIVRAISON_A_DOMICILE
                ]), //Commande type_livraison

                self::$faker->email(), //Commande mail_client

                0, //Commande montant

                0, //Commande delai

                [], //Commande itemsDTO

                Commande::ETAT_CREE //Commande etat

            );

            for ($j = 0; $j < self::$faker->numberBetween(1, 5); $j++) {

                $Random_Produit = self::$serviceProduits->getProduit(
                    self::$faker->numberBetween(1, 10),
                    self::$faker->numberBetween(1, 2)
                );

                $itemDTO = new ItemDTO(
                    Produit::where('numero', $Random_Produit->numero_produit)
                        ->firstOrFail()->id, //Item id

                    $Random_Produit->numero_produit, //Item numero

                    $Random_Produit->libelle_produit, //Item libelle

                    Taille::where('libelle', $Random_Produit->libelle_taille)
                        ->firstOrFail()->id, //Item taille

                    self::$faker->numberBetween(1, 5), //Item quantite

                    $Random_Produit->tarif //Item prix

                );

                $commandeDTO->addItem($itemDTO);

            }

            self::$commandeIds[] = $commandeDTO->getId();

            $commandeDTO_DBRESPONSE = self::$serviceCommande->creerCommande($commandeDTO);

            self::assertEquals(
                $commandeDTO->getDate(), $commandeDTO_DBRESPONSE->getDate()
            );

            self::assertEquals(
                $commandeDTO->getTypeLivraison(), $commandeDTO_DBRESPONSE->getTypeLivraison()
            );

            self::assertEquals(
                $commandeDTO->getMailClient(), $commandeDTO_DBRESPONSE->getMailClient()
            );

            self::assertEquals(
                $commandeDTO->getMontant(), $commandeDTO_DBRESPONSE->getMontant()
            );

            self::assertEquals(
                $commandeDTO->getDelai(), $commandeDTO_DBRESPONSE->getDelai()
            );

            self::assertEquals(
                $commandeDTO->getEtat(), $commandeDTO_DBRESPONSE->getEtat()
            );

        }

    }


    public function testGetCommande(){
        //$id = self::$commandeIds[0];
        foreach (self::$commandeIds as $id){

            $commandeEntity = Commande::find($id);
            $commandeDTO = self::$serviceCommande->accederCommande($id);

            $this->assertNotNull($commandeDTO);
            $this->assertNotNull($commandeEntity);

            $this->assertEquals($id, $commandeDTO->getId());
            $this->assertEquals($commandeEntity->mail_client, $commandeDTO->getMailClient());
            $this->assertEquals($commandeEntity->etat, $commandeDTO->getEtat()); // TODO: check if this is correct
            $this->assertEquals($commandeEntity->type_livraison, $commandeDTO->getTypeLivraison());
            $this->assertEquals($commandeEntity->montant_total, $commandeDTO->getMontant());
            $this->assertEquals(count($commandeEntity->items), count($commandeDTO->getItemsDTO()));
        }

    }

    public function testValiderCommande(){
        foreach (self::$commandeIds as $id){
            $commandeDTO = self::$serviceCommande->validerCommande($id);
            $this->assertEquals(Commande::ETAT_VALIDE, $commandeDTO->getEtat());
        }
    }

}